package harschr.selfmotivator.gui;

import javax.swing.JOptionPane;
import harschr.selfmotivator.dao.impl.*;
import harschr.selfmotivator.model.Training;

public class NewTraining extends javax.swing.JFrame {

    SelfMotivatorRepositoryJDBCimpl trDAO = new SelfMotivatorRepositoryJDBCimpl();

    int length_training1;
    int length_training2;
    int length_training3;
    int length_training4;
    int length_training5;
    
    public NewTraining() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_header = new javax.swing.JLabel();
        lb_name = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        lb_activity = new javax.swing.JLabel();
        tf_activity1 = new javax.swing.JTextField();
        lb_length = new javax.swing.JLabel();
        tf_length1 = new javax.swing.JTextField();
        lb_break = new javax.swing.JLabel();
        tf_break = new javax.swing.JTextField();
        lb_sec = new javax.swing.JLabel();
        lb_sec2 = new javax.swing.JLabel();
        lb_recurrence = new javax.swing.JLabel();
        tf_recurrence = new javax.swing.JTextField();
        lb_times = new javax.swing.JLabel();
        bt_ok = new javax.swing.JButton();
        bt_exit = new javax.swing.JButton();
        lb_activity1 = new javax.swing.JLabel();
        lb_activity2 = new javax.swing.JLabel();
        lb_activity3 = new javax.swing.JLabel();
        tf_activity2 = new javax.swing.JTextField();
        lb_length1 = new javax.swing.JLabel();
        tf_length2 = new javax.swing.JTextField();
        lb_sec1 = new javax.swing.JLabel();
        lb_activity4 = new javax.swing.JLabel();
        lb_activity5 = new javax.swing.JLabel();
        tf_activity3 = new javax.swing.JTextField();
        lb_length2 = new javax.swing.JLabel();
        tf_length3 = new javax.swing.JTextField();
        lb_sec3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lb_activity6 = new javax.swing.JLabel();
        lb_activity7 = new javax.swing.JLabel();
        tf_activity4 = new javax.swing.JTextField();
        lb_length3 = new javax.swing.JLabel();
        tf_length4 = new javax.swing.JTextField();
        lb_sec4 = new javax.swing.JLabel();
        lb_activity8 = new javax.swing.JLabel();
        lb_activity9 = new javax.swing.JLabel();
        tf_activity5 = new javax.swing.JTextField();
        lb_length4 = new javax.swing.JLabel();
        tf_length5 = new javax.swing.JTextField();
        lb_sec5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SELFMOTIVATOR");

        lb_header.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lb_header.setText("Dane nowego treningu:");

        lb_name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_name.setText("Nazwa:");

        lb_activity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_activity.setText("Czynność:");

        lb_length.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_length.setText("Długość treningu:");

        lb_break.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_break.setText("Długość przerwy:");

        lb_sec.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_sec.setText("sek");

        lb_sec2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_sec2.setText("sek");

        lb_recurrence.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_recurrence.setText("Częstotliwość:");

        lb_times.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_times.setText("razy");

        bt_ok.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bt_ok.setText("OK");
        bt_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_okActionPerformed(evt);
            }
        });

        bt_exit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bt_exit.setText("Wyjść");
        bt_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_exitActionPerformed(evt);
            }
        });

        lb_activity1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lb_activity1.setText("Czynność nr.1.:");

        lb_activity2.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lb_activity2.setText("Czynność nr.2.:");

        lb_activity3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_activity3.setText("Czynność:");

        lb_length1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_length1.setText("Długość treningu:");

        lb_sec1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_sec1.setText("sek");

        lb_activity4.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lb_activity4.setText("Czynność nr.3.:");

        lb_activity5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_activity5.setText("Czynność:");

        lb_length2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_length2.setText("Długość treningu:");

        lb_sec3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_sec3.setText("sek");

        lb_activity6.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lb_activity6.setText("Czynność nr.4.:");

        lb_activity7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_activity7.setText("Czynność:");

        lb_length3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_length3.setText("Długość treningu:");

        lb_sec4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_sec4.setText("sek");

        lb_activity8.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lb_activity8.setText("Czynność nr.5.:");

        lb_activity9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_activity9.setText("Czynność:");

        lb_length4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_length4.setText("Długość treningu:");

        lb_sec5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_sec5.setText("sek");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_header, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_length)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_length1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_sec, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_break)
                                    .addComponent(lb_recurrence))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tf_recurrence, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lb_times, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tf_break, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lb_sec2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lb_name, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_activity, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_activity1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lb_activity1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_length1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_length2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_sec1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_activity3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_activity2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lb_activity2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_length2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_length3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_sec3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_activity5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_activity3, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lb_activity4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_length3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_length4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_sec4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_activity7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_activity4, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lb_activity6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_length4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_length5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_sec5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_activity9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_activity5, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lb_activity8, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(bt_ok)
                        .addGap(100, 100, 100)
                        .addComponent(bt_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lb_header, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_name)
                    .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(lb_activity1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_activity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_activity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_length)
                    .addComponent(tf_length1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_sec))
                .addGap(10, 10, 10)
                .addComponent(lb_activity2)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_activity2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_activity3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_length1)
                    .addComponent(tf_length2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_sec1))
                .addGap(10, 10, 10)
                .addComponent(lb_activity4)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_activity3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_activity5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_length2)
                    .addComponent(tf_length3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_sec3))
                .addGap(10, 10, 10)
                .addComponent(lb_activity6)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_activity4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_activity7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_length3)
                    .addComponent(tf_length4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_sec4))
                .addGap(10, 10, 10)
                .addComponent(lb_activity8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_activity5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_activity9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_length4)
                    .addComponent(tf_length5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_sec5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_break)
                    .addComponent(tf_break, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_sec2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_recurrence)
                    .addComponent(tf_recurrence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_times, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_exitActionPerformed
        dispose();
        new Start().setVisible(true);
    }//GEN-LAST:event_bt_exitActionPerformed

    private void bt_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_okActionPerformed
        recordTraining();
    }//GEN-LAST:event_bt_okActionPerformed

    private void recordTraining() {
        if (tf_name.getText().isBlank() || tf_activity1.getText().isBlank() || tf_length1.getText().isBlank() || tf_break.getText().isBlank() || tf_recurrence.getText().isBlank()) {
            showError();
        } else {

            String name = tf_name.getText();
            String activity1 = tf_activity1.getText();
            length_training1 = Integer.valueOf(tf_length1.getText());
            
            String activity2 = tf_activity2.getText();
            if (tf_length2.getText().isBlank()) {
            length_training2 = 0;
            } else {
            length_training2 = Integer.valueOf(tf_length2.getText());
            }
            
            String activity3 = tf_activity3.getText();
            if (tf_length3.getText().isBlank()) {
            length_training3 = 0;
            } else {
            length_training3 = Integer.valueOf(tf_length3.getText());
            }
            
            String activity4 = tf_activity4.getText();
             if (tf_length4.getText().isBlank()) {
            length_training4 = 0;
            } else {
            length_training4 = Integer.valueOf(tf_length4.getText());
            }
             
            String activity5 = tf_activity5.getText();
            if (tf_length5.getText().isBlank()) {
            length_training5 = 0;
            } else {
            length_training5 = Integer.valueOf(tf_length5.getText());
            }
            
            int length_break = Integer.valueOf(tf_break.getText());
            int recurrence = Integer.valueOf(tf_recurrence.getText());
            Training tr = new Training(name, activity1, length_training1, activity2, length_training2, activity3, length_training3, activity4, length_training4, activity5, length_training5, length_break, recurrence);
            tf_name.requestFocusInWindow();
            trDAO.insert(tr);
            JOptionPane.showMessageDialog(this, "Trening zapisane!");

            tf_name.setText("");
            tf_activity1.setText("");
            tf_length1.setText("");
            tf_activity2.setText("");
            tf_length2.setText("");
            tf_activity3.setText("");
            tf_length3.setText("");
            tf_activity4.setText("");
            tf_length4.setText("");
            tf_activity5.setText("");
            tf_length5.setText("");
            tf_break.setText("");
            tf_recurrence.setText("");
            dispose();
            new ListAllTrainings().setVisible(true);
        }
    }

    private void showError() {
        JOptionPane.showInternalMessageDialog(null, "Przynajmniej 1 czynność oraz długość przerwy i częstotliwość muszą być uzupełnione!", "Uwaga!", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewTraining.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewTraining.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewTraining.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewTraining.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewTraining().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_exit;
    private javax.swing.JButton bt_ok;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lb_activity;
    private javax.swing.JLabel lb_activity1;
    private javax.swing.JLabel lb_activity2;
    private javax.swing.JLabel lb_activity3;
    private javax.swing.JLabel lb_activity4;
    private javax.swing.JLabel lb_activity5;
    private javax.swing.JLabel lb_activity6;
    private javax.swing.JLabel lb_activity7;
    private javax.swing.JLabel lb_activity8;
    private javax.swing.JLabel lb_activity9;
    private javax.swing.JLabel lb_break;
    private javax.swing.JLabel lb_header;
    private javax.swing.JLabel lb_length;
    private javax.swing.JLabel lb_length1;
    private javax.swing.JLabel lb_length2;
    private javax.swing.JLabel lb_length3;
    private javax.swing.JLabel lb_length4;
    private javax.swing.JLabel lb_name;
    private javax.swing.JLabel lb_recurrence;
    private javax.swing.JLabel lb_sec;
    private javax.swing.JLabel lb_sec1;
    private javax.swing.JLabel lb_sec2;
    private javax.swing.JLabel lb_sec3;
    private javax.swing.JLabel lb_sec4;
    private javax.swing.JLabel lb_sec5;
    private javax.swing.JLabel lb_times;
    private javax.swing.JTextField tf_activity1;
    private javax.swing.JTextField tf_activity2;
    private javax.swing.JTextField tf_activity3;
    private javax.swing.JTextField tf_activity4;
    private javax.swing.JTextField tf_activity5;
    private javax.swing.JTextField tf_break;
    private javax.swing.JTextField tf_length1;
    private javax.swing.JTextField tf_length2;
    private javax.swing.JTextField tf_length3;
    private javax.swing.JTextField tf_length4;
    private javax.swing.JTextField tf_length5;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_recurrence;
    // End of variables declaration//GEN-END:variables
}
